hector_pose_estimation_core: fix build error in Ubuntu Bionic
The result of the expression is an Eigen type that cannot be converted to double directly in
Eigen 3.3.4:

/opt/hector/melodic/src/hector_localization/hector_pose_estimation_core/src/measurements/poseupdate.cpp: In instantiation of ‘double hector_pose_estimation::PoseUpdate::updateInternal(hector_pose_estimation::State&, const NoiseVariance&, const MeasurementVector&, const MeasurementMatrix&, const string&, double, hector_pose_estimation::PoseUpdate::JumpFunction) [with MeasurementVector = Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<double, double>, const Eigen::Matrix<double, 1, 1, 0, 1, 1>, const Eigen::Matrix<double, 1, 1, 0, 1, 1> >; MeasurementMatrix = Eigen::Matrix<double, 1, -1, 1, 1, 18>; NoiseVariance = Eigen::Matrix<double, 1, 1, 0, 1, 1>; std::__cxx11::string = std::__cxx11::basic_string<char>; hector_pose_estimation::PoseUpdate::JumpFunction = boost::function<void(hector_pose_estimation::State&, const Eigen::Matrix<double, -1, 1, 0, 19, 1>&)>]’:
/opt/hector/melodic/src/hector_localization/hector_pose_estimation_core/src/measurements/poseupdate.cpp:201:181:   required from here
/opt/hector/melodic/src/hector_localization/hector_pose_estimation_core/src/measurements/poseupdate.cpp:385:12: error: cannot convert ‘Eigen::internal::enable_if<true, const Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<double, double>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, const Eigen::Matrix<double, 1, 1, 0, 1, 1> >, const Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<double, double>, const Eigen::Matrix<double, 1, 1, 0, 1, 1>, const Eigen::Matrix<double, 1, 1, 0, 1, 1> > > >::type {aka const Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<double, double>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, const Eigen::Matrix<double, 1, 1, 0, 1, 1> >, const Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<double, double>, const Eigen::Matrix<double, 1, 1, 0, 1, 1>, const Eigen::Matrix<double, 1, 1, 0, 1, 1> > >}’ to ‘double’ in initialization
     double error2 = error.transpose() * Ix * (Ix + Iy).inverse() * Iy * error;
            ^~~~~~
/opt/hector/melodic/src/hector_localization/hector_pose_estimation_core/src/measurements/poseupdate.cpp: In instantiation of ‘double hector_pose_estimation::PoseUpdate::updateInternal(hector_pose_estimation::State&, const NoiseVariance&, const MeasurementVector&, const MeasurementMatrix&, const string&, double, hector_pose_estimation::PoseUpdate::JumpFunction) [with MeasurementVector = Eigen::Matrix<double, 1, 1, 0, 1, 1>; MeasurementMatrix = Eigen::Matrix<double, 1, -1, 1, 1, 18>; NoiseVariance = Eigen::Matrix<double, 1, 1, 0, 1, 1>; std::__cxx11::string = std::__cxx11::basic_string<char>; hector_pose_estimation::PoseUpdate::JumpFunction = boost::function<void(hector_pose_estimation::State&, const Eigen::Matrix<double, -1, 1, 0, 19, 1>&)>]’:
/opt/hector/melodic/src/hector_localization/hector_pose_estimation_core/src/measurements/poseupdate.cpp:234:154:   required from here
/opt/hector/melodic/src/hector_localization/hector_pose_estimation_core/src/measurements/poseupdate.cpp:385:12: error: cannot convert ‘Eigen::internal::enable_if<true, const Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<double, double>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, const Eigen::Matrix<double, 1, 1, 0, 1, 1> >, const Eigen::Matrix<double, 1, 1, 0, 1, 1> > >::type {aka const Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<double, double>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, const Eigen::Matrix<double, 1, 1, 0, 1, 1> >, const Eigen::Matrix<double, 1, 1, 0, 1, 1> >}’ to ‘double’ in initialization